language: ruby

rvm:
  - 2.3.0

addons:
  ssh_known_hosts: blog.liveneeq.com

before_install:
  - sed -i "/^source/c source \'https://rubygems.org\'" Gemfile
  - openssl aes-256-cbc -K $encrypted_edca024af890_key -iv $encrypted_edca024af890_iv -in .deploy/id_rsa.enc -out .deploy/id_rsa -d
  - chmod 600 .deploy/id_rsa

script:
  - JEKYLL_ENV=production bundle exec jekyll build
  - bundle exec htmlproof ./_site --empty-alt-ignore --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: "ejJYt+SkzrDivtYZtXSJQysKXHeIvT9JlauBSAA+PPhDso9Q7AbOd3Bk8T3LQCGeDMO7TARfrNjPKYPDX1XHpnK9LTMThsWPYl4CvOFSRo/G7V4tkgUxCCvAXd0ffd1xJA3mODRiIybGRqqovfIBh1PDU00HzJMlMtF7mVr4+P0BPg09nU6e01Tjmy9rO5p1jcHMQvFdzUAUUNWGFML9+1ZpojlaCOGLDOASNUv6RsxwkP26vA7iOvZG4fzrLf994rm76FMWOlXh3oxlUC+zPfl2Myu+RK8FaFFp0LFxp0VsAA+8hnS8y5TDRJMifiSK/+7FCuEsdz4YjRcbcpXIOZRJ9YeqsS5IVGTcOeNs4RDCLLvvtBIcBUilw0VVjbxWMHmG0XXCqqrwHW6m0p2ucOStEVPpH4gvlKAj2+rARqYmIzo9vwEiCAe3nzV1egl0dzXAkB60NfqEQaqDmhdd4kNWsviFj0fa+mpg7oHmFPzKvHAzr3UUloapB+bQOTgOxA26nVY12tFO81pG6zzi1GvgMsxGeOaW2Yfu8ODfeAA6X41SMONdKsMoxmV3pxgzdOeEsiutj8SzQGhuik8UKKjIvTejBR5U/sKvrBrR3/4SJ6tQQlvgFeb8+qJtKsabogy5H0eEjDFks+3obqy6bY7d3c02KAcL1uFuJZszXJI="

deploy:
  skip_cleanup: true
  provider: script
  script: rsync -vrthu --checksum --delete -e 'ssh -i .deploy/id_rsa' _site/* $deploy_to
  on:
    branch: master
