# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liveneeq Blog
description: Techblog of liveneeq
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.liveneeq.com" # the base hostname & protocol for your site

disqus_shortname: liveneeqblog

# @see http://jekyllrb.com/docs/configuration/
highlighter: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

# GitHub Flavored Markdown
kramdown:
  input: GFM

timezone: 'Asia/Shanghai'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - template
  - auto_update.sh
  - github_webhook.rb
  - config.ru
  - README.md
  - Deployment.md
  - Gemfile
  - Gemfile.lock
  - autoprefixer.yml
  - vendor  # Travis-CI generated directory
  - .deploy

gems:
  - jekyll-assets

assets:
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
  sources:
    - _assets/css
    - _assets/js
    - _assets/images
  features:
    automatic_img_size: false
    automatic_img_alt : false
